AtaliTicaret/AtaliTicaret.WebUI/Models/ErrorViewModel.cs
using System;

namespace AtaliTicaret.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Models/Sepet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AtaliTicaret.WebUI.Models
{
    public static class Sepet
    {

        public static Dictionary<int, int> Ids = new Dictionary<int, int>();

        public static void AddId(int id)
        {
            if (Ids.ContainsKey(id))
            {
                Ids[id] += 1;
            }
            else
            {
                Ids.Add(id, 1);
            }
        }

        public static int ShowSumOfValues()
        {
            return Ids.Values.Sum();
        }


    }
}

AtaliTicaret/AtaliTicaret.WebUI/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtaliTicaret.Business.Abstract;
using AtaliTicaret.Entites.Concrete;
using AtaliTicaret.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace AtaliTicaret.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IProductService _productService;

        public BasketController(IProductService x)
        {
            _productService = x;
        }

        public IActionResult Index()
        {

            List<int> keys = Sepet.Ids.Keys.ToList();

            var entity = _productService.GetProductsFromInTheBasket(keys);

            return View(entity);
        }

        public IActionResult AddProductForBasket(int ProductId,string reUrl)
        {

            Sepet.AddId(ProductId);

            return Redirect(reUrl);
        }

        public IActionResult ClearBasket()
        {
            Sepet.Ids.Clear();

            return RedirectToAction("Index");
        }

        public IActionResult IncreaseProduct(int id)
        {

            if (Sepet.Ids.ContainsKey(id))
            {
                Sepet.Ids[id] += 1;
            }

            return RedirectToAction("Index");
        }

        public IActionResult DecreaseProduct(int id)
        {
            if (Sepet.Ids.ContainsKey(id))
            {
                Sepet.Ids[id] -= 1;

                if(Sepet.Ids[id] == 0)
                {
                    Sepet.Ids.Remove(id);
                }
            }

            return RedirectToAction("Index");
        }



    }
}

AtaliTicaret/AtaliTicaret.WebUI/Controllers/DealerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtaliTicaret.Business.Abstract;
using AtaliTicaret.Entites.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace AtaliTicaret.WebUI.Controllers
{
    public class DealerController : Controller
    {
        IDealerService _dealerService;
        IProductService _productService;

        public DealerController(IDealerService x,IProductService y)
        {
            _dealerService = x;
            _productService = y;
        }
        public IActionResult Index()
        {
            return View(_dealerService.GetEntities(null));
        }
        public IActionResult Details(int id)
        {

            Dealer entity = _dealerService.GetEntity(c => c.DealerId == id);
            entity.Products = _productService.GetEntities(c => c.DealerId == id);

            return View(entity);
        }
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AtaliTicaret.WebUI.Models;
using AtaliTicaret.Business.Abstract;

namespace AtaliTicaret.WebUI.Controllers
{
    public class HomeController : Controller
    {
        IProductService _productServis;

        public HomeController(IProductService x)
        {
            _productServis = x;
        }

        public IActionResult Index()
        {
            return View(_productServis.GetEntities(null));
        }
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtaliTicaret.Business.Abstract;
using AtaliTicaret.DataAccess.Concrete.EntityFramework;
using AtaliTicaret.Entites.Concrete;
using AtaliTicaret.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace AtaliTicaret.WebUI.Controllers
{
    public class ProductController : Controller
    {

        IProductService _productService;
        IDealerService _dealerService;

        public ProductController(IProductService x,IDealerService y)
        {
            _productService = x;
            _dealerService = y;


        }

        public IActionResult Index()
        {
            return Redirect("/Home/Index/");
        }

        public IActionResult Details(int id)
        {

            TempData["url"] = "/Product/Details/"+id.ToString()+"/";

            Product entity = _productService.GetEntity(c => c.ProductId == id);
            entity.Dealer = _dealerService.GetEntity(c => c.DealerId == entity.DealerId);

            return View(entity);
        }

        public IActionResult CategoryProductsList(int id)
        {
            return View(_productService.GetEntities(c => c.CategoryId == id));
        }

        public IActionResult WantedKey(string key)
        {
            return View("CategoryProductsList",_productService.GetEntities(c => c.ProductName.Contains(key)));
        }
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Views/Basket/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";


    double sumOfPrice = 0.0;

}


<div class="text-center">
    <h3 class="display-3">Sepetim</h3>
</div>

<table class="table table-striped table-sm table-bordered mt-5">
    <thead>
        <tr>
            <th scope="colgroup" class="text-center">Ürün Açıklama</th>
            <th scope="colgroup" class="text-center">Ürün Adet</th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Count() != 0)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <p class="text-black-50">
                            <img src="~/img/@item.ProductPhotoUrl" class="rounded float-left w-auto" height="150" width="150" alt="...">
                            <div class="mt-2">
                                <span class="h5 text-info ml-4 w-auto">Ürün Başlık&nbsp;:&nbsp;</span><span class="text-dark">@item.ProductTitle</span>
                            </div>
                            <div class="mt-2">
                                <span class="h5 text-info ml-4 w-auto">Ürün Fiyat&nbsp;:&nbsp;</span><span class="text-dark">@item.ProductPrice.ToString()&nbsp;&#8378;</span>
                            </div>
                            <div class="mt-2">
                                <a href="/Product/Details/@item.ProductId" class="btn ml-4 w-auto" style="background-color:darkkhaki;">Ürün detayına tekrardan göz at!</a>
                            </div>
                        </p>
                    </td>
                    <td>
                        <div class="text-center mt-3 mx-auto">
                            @{
                                int deger = 0;

                                if (Sepet.Ids.ContainsKey(item.ProductId))
                                {
                                    deger = Sepet.Ids[item.ProductId];
                                }


                                sumOfPrice = sumOfPrice + (deger * (Convert.ToDouble(item.ProductPrice)));

                            }

                            <div class="font-weight-bold">
                                @deger.ToString()
                            </div>
                            <div class="mt-4">
                                <a asp-controller="Basket" asp-action="IncreaseProduct" asp-route-id="@item.ProductId" class="btn btn-outline-success">Arttır</a>
                                <a asp-controller="Basket" asp-action="DecreaseProduct" asp-route-id="@item.ProductId" class="btn btn-outline-danger">Azalt</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

            <tr>
                <td colspan="2">
                    <div class="mt-4 mr-4">
                        <p class="d-flex justify-content-end"><span class="h5">Toplam Fiyat&nbsp;:&nbsp;</span><span class="mr-5">@sumOfPrice.ToString("0.00")&nbsp;&#8378;</span></p>
                        <div class="d-flex justify-content-end">
                            <a onclick="Yaz()" asp-action="ClearBasket" asp-controller="Basket" class="btn btn-success">Ödemeyi Tamamla</a>
                            <a onclick="Yaz1()" asp-action="ClearBasket" asp-controller="Basket" class="ml-3 btn btn-danger">Sepeti Temizle</a>
                        </div>
                    </div>
                </td>
            </tr>
         }
         else 
            {
                <tr>
                    <td colspan="2">
                        <div class="alert alert-danger text-center">
                            <span class="display-4">Sepetinizde Ürün Yok!</span>
                        </div>
                    </td>
                </tr>
            }


    </tbody>
</table>

<script>
    function Yaz() {
        alert("Satın Alımlarınız İçin Teşekkürler!");
    }
    function Yaz1() {
        alert("Sepetiniz Temizlendi!");
    }
</script>

AtaliTicaret/AtaliTicaret.WebUI/Views/Dealer/Details.cshtml
@model Dealer
@{
    ViewData["Title"] = "Details";
}

<div class="card text-center">
    <div class="card-header">
        GeldiGeliyorSatıcısı
    </div>
    <div class="card-body">
        <img src="~/img/@Model.DealerLogoUrl" class="card-img-top w-50" height="200" />
        <div class="card-body">
            <h5 class="card-title">@Model.DealerName</h5>
            <p class="card-text">Adres&nbsp;:&nbsp;@Model.DealerAdress</p>
            <p class="card-text">Telefon&nbsp;:&nbsp;@Model.DealerTel</p>
        </div>
        <div class="card-footer text-muted">
            GeldiGeliyor Kalitesiyle...
        </div>
    </div>
</div>
<ul class="list-group mt-3">
    @if (Model.Products.Count() > 0)
    {
        <li class="list-group-item disabled" style="background-color:blueviolet; color:white;" aria-disabled="true">Satıcının Ürünleri</li>
        @foreach (Product item in Model.Products)
        {
            <li class="list-group-item">
                <a asp-route-id="@item.ProductId" asp-controller="Product" asp-action="Details">
                    @item.ProductTitle
                </a>
            </li>
        }
    }
    else
    {
        <li class="list-group-item">
            <div class="alert text-center alert-danger text-white">Satıcının Sisteme Kayıtlı Ürünü Yoktur</div>
        </li>
    }
</ul>

AtaliTicaret/AtaliTicaret.WebUI/Views/Dealer/Index.cshtml
@model List<Dealer>
@{
    ViewData["Title"] = "Index";
}

@for (int i = 0; i < Model.Count(); i++)
{
    if (i % 3 == 0)
    {
        <div class="card-group">
            @{
                int gidilecek = i + 3;

                if (gidilecek > Model.Count())
                {
                    gidilecek = Model.Count();
                }
            }

            @for (int j = i; j < gidilecek; j++)
            {
                <div class="card border text-center mt-3 ml-2">
                    <img src="~/img/@Model[j].DealerLogoUrl" class="card-img-top"  height="300" alt="@Model[j].DealerName">
                    <div class="card-body text-center">
                        <h5 class="card-title">@Model[j].DealerName</h5>
                        <p class="card-text"><span class="text-info h4">@Model[j].DealerAdress</span></p>
                        <p class="card-text">Telefon&nbsp;:&nbsp;@Model[j].DealerTel</p>

                    </div>
                    <div class="card-footer text-center">
                        <a class="btn btn-outline-primary" asp-action="Details" asp-controller="Dealer" asp-route-id="@Model[j].DealerId">Satıcı Detaylarına Göz At</a>
                    </div>
                </div>
            }
        </div>
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Views/Home/Index.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Home Page";
}

@for (int i = 0; i < Model.Count(); i++)
{
    if (i % 3 == 0)
    {
        <div class="card-group">
            @{
                int gidilecek = i + 3;

                if(gidilecek > Model.Count())
                {
                    gidilecek = Model.Count();
                }
            }
                @for (int j = i; j < gidilecek; j++)
                {
                    <div class="card border mt-3 ml-2">
                        <img src="~/img/@Model[j].ProductPhotoUrl" style=""  class="card-img-top" height="280" width="200" alt="@Model[j].ProductName">
                        <div class="card-body text-center">
                            <h5 class="card-title">@Model[j].ProductTitle</h5>
                            <p class="card-text"><span class="text-info h4">@Model[j].ProductPrice.ToString()&nbsp;&#8378;</span></p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-primary" asp-action="Details" asp-controller="Product" asp-route-id="@Model[j].ProductId">Ürünü İncele</a>
                        </div>
                    </div>
                }
            </div>
    }
 }

AtaliTicaret/AtaliTicaret.WebUI/Views/Product/CategoryProductsList.cshtml
@model List<Product>
@{
    ViewData["Title"] = "CategoryProductsList";
}

@if (@Model.Count() == 0)
{
    <p class="alert-danger">Opss... Aradığın bulunamadı!!</p>

}
else
{
    @for (int i = 0; i < Model.Count(); i++)
    {
        if (i % 3 == 0)
        {
            <div class="card-group">
                @{
                    int gidilecek = i + 3;

                    if (gidilecek > Model.Count())
                    {
                        gidilecek = Model.Count();
                    }
                }
                @for (int j = i; j < gidilecek; j++)
                {
                    <div class="card border mt-3 ml-2">
                        <img src="~/img/@Model[j].ProductPhotoUrl" class="card-img-top mx-auto" height="300" width="150" alt="@Model[j].ProductName">
                        <div class="card-body text-center">
                            <h5 class="card-title">@Model[j].ProductTitle</h5>
                            <p class="card-text"><span class="text-info h4">@Model[j].ProductPrice.ToString()&nbsp;&#8378;</span></p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-primary" asp-action="Details" asp-controller="Product" asp-route-id="@Model[j].ProductId">Ürünü İncele</a>
                        </div>
                    </div>
                }
            </div>
        }
    }
}

AtaliTicaret/AtaliTicaret.WebUI/Views/Product/Details.cshtml
@model Product
@{
    ViewData["Title"] = "Details";

}


    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="~/img/@Model.ProductPhotoUrl" class="img-thumbnail" alt="@Model.ProductName">
            </div>
            <div class="col-md-6 mt-5">
                <p class="h5">Ürün Başlığı&nbsp;:&nbsp;@Model.ProductTitle</p>
                <p class="h5"><span class="h5 text-primary">Ürün Adı&nbsp;:&nbsp;</span>@Model.ProductName</p>
                <a asp-controller="Dealer" asp-action="Details" asp-route-id="@Model.DealerId"><span class="h5 text-primary text-decoration-none">Satıcı&nbsp;:&nbsp;</span>@Model.Dealer.DealerName</a>
                <p class="h5">
                    <span class="h5 text-primary">Ürün Fiyatı&nbsp;:&nbsp;</span>@Model.ProductPrice.ToString()&nbsp;&#8378;
                </p>
                <form class="mt-3" asp-controller="Basket" asp-action="AddProductForBasket" method="post">
                    <input hidden type="text" id="reUrl" name="reUrl" value="@TempData["url"]" />
                    <input hidden type="text" id="ProductId" name="ProductId" value="@Model.ProductId" />
                    <input type="submit" class="btn btn-warning" value="Ekle" />
                </form>
            </div>
        </div>
        <div class="row mt-3 border-top box-shadow">
            <div class="col">
                <p class="h5 font-weight-bold">Ürün Açıklaması</p>
                <p>&nbsp;&nbsp;@Model.ProductDescription</p>
            </div>
        </div>
    </div>

AtaliTicaret/AtaliTicaret.WebUI/Views/Shared/Components/CategoriesSum/Default.cshtml
@model List<Category>
@{
    Layout = null;
}

<div class="row">
    <div class="col">
        <ul class="list-group">
            <li class="list-group-item disabled" style="background-color: blueviolet;"><span class="font-weight-bold h5" style="color:white;">Kategoriler</span></li>  
            @foreach (Category category in Model)
            {
                <li class="list-group-item">
                    <a asp-action="CategoryProductsList" asp-controller="Product" asp-route-id="@category.CategoryId" >@category.CategoryName&nbsp; (@category.Products.Count())</a>
                </li>
            }
        </ul>
    </div>
</div>

AtaliTicaret/AtaliTicaret.WebUI/Views/Shared/Components/SepetUrunSayisi/Default.cshtml
@model int

<b>@Model.ToString()</b>

AtaliTicaret/AtaliTicaret.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtaliTicaret.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <style>
        .anaNavLink {
            color: #ecf0f1;
            font-weight: bold;
        }

        .anaNavLink:hover{
            transition : 0.6s;
            color : greenyellow;
        }

        .basNavLink {
            color: #ecf0f1;
            font-weight: bold;
        }

        #markaTex {
            font-family: 'Lobster', cursive;
            color: #ecf0f1;
            font-weight: bold;
        }

        #navYazi {
            color: #27ae60;
            font-family: 'Pacifico', cursive;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color:#2c3e50;">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 mx-auto">
                        <li class="nav-item ml-5">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><span class="basNavLink"><i class="fas fa-store">&nbsp;<span id="markaTex">GeldiGeliyor.com</span></i></span></a>
                        </li>
                        <li class="nav-item mx-auto" id="navYazi">
                            <a class="nav-link disabled">İyi Alışverişler</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><span class="anaNavLink">Anasayfa</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Dealer" asp-action="Index"><span class="anaNavLink">Satıcılar</span></a>
                        </li>
                        <li class="nav-item mr-3">
                            <a href="/Basket/Index/" style="background-color:#2c3e50;"  class="btn btn-primary">
                                <i class="fas fa-shopping-cart"></i>&nbsp; Sepetim &nbsp;<span class="badge bg-secondary">
                           @await Component.InvokeAsync("SepetUrunSayisi")
                            </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <form class="d-flex" asp-controller="Product" asp-action="WantedKey" method="get">
                                <input id="key" name="key" class="form-control me-2" type="search" placeholder="Aranacak Ürün Adı" aria-label="Search">
                                <button class="ml-2 btn btn-outline-success" type="submit">Ara</button>
                            </form>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                @await Component.InvokeAsync("CategoriesSum")
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top mt-5 modal-footer text-muted">
        <div class="container mt-3 text-center">
            &copy; 2021 - Bu Sitenin Tüm Hakları Bilgisayar Mühendisi Adayı Haruncan Atalı Tarafından Saklıdır.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>